### PR TITLE
waf_rule_group rule label support

### PR DESCRIPTION
**Pull request by irussak3**

### CODE REVIEW

**Comment by irussak3** [comment]
@uyggnodoow @semantic-release-bot

**Comment by uyggnodoow** [comment]
This PR is included in version 3.1.0 :tada:

**Comment by uyggnodoow** [comment]
Hello @irussak3 

Thanks for your Pull Request. 
Perhaps the rule_label argument is affected by the provider version. Let us know if you run into any issues.

**Comment by irussak3** [comment]
@uyggnodoow From my review the action exists under the current version so it shouldn't be a problem 🔥

**Comment by tal-lederman-dy** [comment]
Very useful! Thanks, @irussak3 :)

**Pull request merged**
