### PR TITLE
Fixed rate_based capabilities and added custom_keys capabilities

### PR DESCRIPTION
**Pull request by irussak3**

### CODE REVIEW

**Comment by irussak3** [comment]
@uyggnodoow 🙏

**Comment by irussak3** [comment]
When tried to use rate_based statements I got empty statements now it works

**Comment by uyggnodoow** [comment]
Hello @irussak3 

Sorry for the late response. I will test it that you requested code.

**Comment by uyggnodoow** [comment]
Hello @irussak3 

Sorry for the late response, I've updated the 'custom_keys' argument in the rate_based_statement to be usable.
You can use v3.6.0 and I've updated example codes too.

**Pull request closed without merging**
